variables:
    VLC_UWP_LLVM_IMAGE: registry.videolan.org/vlc-debian-llvm-uwp:20211020111246
    VLC_VERSION: 3.0.20
    UWP_LIBVLC_BUILD_FLAGS: -z -r -u -w

.variables-win32: &variables-win32
        SHORTARCH: win32
        HOST_ARCH: i686
        TRIPLET: $HOST_ARCH-w64-mingw32
        BUILD_PATH: vlc/$SHORTARCH-uwp/vlc-$VLC_VERSION-$SHORTARCH.7z

.variables-win64: &variables-win64
        SHORTARCH: win64
        HOST_ARCH: x86_64
        TRIPLET: $HOST_ARCH-w64-mingw32
        BUILD_PATH: vlc/$SHORTARCH-uwp/vlc-$VLC_VERSION-$SHORTARCH.7z

.variables-win-arm: &variables-win-arm
        SHORTARCH: winarm
        HOST_ARCH: armv7
        TRIPLET: $HOST_ARCH-w64-mingw32
        BUILD_PATH: vlc/$SHORTARCH-uwp/vlc-$VLC_VERSION-win32.7z

# Common rules for jobs using docker
.docker-template:
    tags:
        - docker
        - amd64

#
# Windows
#
.winrt-common:
    extends: .docker-template
    script: |
        git clone https://code.videolan.org/videolan/vlc && cd vlc && git checkout 3.0.x
        git config --global user.email "cone@example.com"
        git config --local user.name "Cony Cone"
        git am -3 ../patches/*.patch
        if [ $? -ne 0 ]; then
            git am --abort
            echo "Applying the patches failed, aborting git-am"
            exit 1
        fi
        extras/package/win32/build.sh -c -a $HOST_ARCH $UWP_LIBVLC_BUILD_FLAGS

.nightly-winrt-common:
    extends: .winrt-common
    artifacts:
        paths:
            - $BUILD_PATH
uwp-x64:
    extends: .nightly-winrt-common
    image:
        name: $VLC_UWP_LLVM_IMAGE
    variables:
        <<: *variables-win64

uwp-x86:
    extends: .nightly-winrt-common
    image:
        name: $VLC_UWP_LLVM_IMAGE
    variables:
        <<: *variables-win32

uwp-arm:
    extends: .nightly-winrt-common
    image:
        name: $VLC_UWP_LLVM_IMAGE
    variables:
        <<: *variables-win-arm